# Generated by Django 5.2.8 on 2025-12-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_damypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damypayment',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20),
        ),
    ]
